# Generated by Django 4.2 on 2023-04-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('role', models.IntegerField(choices=[(1, 'Admin'), (2, 'Author')], default=3)),
                ('profile_picture', models.ImageField(upload_to='profiles-pictures/')),
            ],
        ),
    ]
