# Generated by Django 4.2 on 2023-04-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), (2, 'Published'), (3, 'Archived'), (4, 'Schedule')], max_length=50),
        ),
    ]
