# Generated by Django 4.2 on 2023-04-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_remove_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
