# Generated by Django 4.2 on 2023-04-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_alter_posts_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='breaking_news',
            field=models.BooleanField(null=True),
        ),
    ]
