# Generated by Django 4.2 on 2023-04-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_categories_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=50)),
            ],
        ),
    ]
