# Generated by Django 4.2 on 2023-04-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='facebook_link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='instagram_link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='twitter_link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
