# Generated by Django 4.2 on 2023-04-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_site_facebook_link_site_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='youtube_link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
