# Generated by Django 4.2 on 2023-04-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_site_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_logo',
            field=models.ImageField(blank=True, upload_to='sitelogo/'),
        ),
    ]
