# Generated by Django 4.2 on 2023-04-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_site_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='favicon/'),
        ),
    ]
