# Generated by Django 4.2 on 2023-04-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_posts_author_posts_breaking_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='page_views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
