# Generated by Django 4.2 on 2023-04-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0011_alter_posts_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
