# Generated by Django 4.2 on 2023-04-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0012_site_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
