# Generated by Django 4.2 on 2023-04-09 07:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0013_site_address_site_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='breaking_news',
        ),
        migrations.AddField(
            model_name='posts',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
