# Generated by Django 4.2 on 2023-04-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0015_alter_posts_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='tags',
        ),
    ]
